---
- name: generate_secret_token
  command: /usr/local/rbenv/shims/bundle exec rake generate_secret_token
  args:
    chdir: "{{ redmine_dir }}"

- name: Migrate Database
  command: /usr/local/rbenv/shims/bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production

- name: Setup Database
  command: /usr/local/rbenv/shims/bundle exec rake redmine:load_default_data
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
    REDMINE_LANG: ja
