---
- name: Install and configure the basic package
  hosts: all
  become: true

  roles:
    - role: common
      tags: common
    - role: sdkman
      tags: sdkman
    - role: grails
      tags: grails
    - role: postgres
      tags: postgres
    - role: phppgadmin
      tags: phppgadmin
    - role: vim
      tags: vim
